server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cowrie
    static_configs:
      - targets:
          - localhost
        labels:
          job: cowrie
          __path__: /var/log/cowrie/cowrie.json*
    pipeline_stages:
      - json:
          expressions:
            eventid: eventid
            src_ip: src_ip
            username: username
            password: password
            input: input
      - labels:
          eventid:
          src_ip:
          username:

  - job_name: opencanary
    static_configs:
      - targets:
          - localhost
        labels:
          job: opencanary
          service: core
          __path__: /var/log/opencanary/opencanary.log*
    pipeline_stages:
      - json:
          expressions:
            logtype: logtype
            src_host: src_host
      - labels:
          logtype:
          src_host:
      - match:
          selector: '{job="opencanary", service="core", logtype=~"3000|3001"}'
          action: drop

  - job_name: opencanary-http
    static_configs:
      - targets:
          - localhost
        labels:
          job: opencanary
          service: http
          __path__: /var/log/opencanary/opencanary.log*
    pipeline_stages:
      - json:
          expressions:
            src_host: src_host
            logtype: logtype
            username: logdata.USERNAME
            password: logdata.PASSWORD
            hostname: logdata.HOSTNAME
            path: logdata.PATH
            user_agent: logdata.USERAGENT
      - labels:
          src_host:
          logtype:
          username:
          password:
          path:
          user_agent:
      - match:
          selector: '{job="opencanary", service="http", logtype!~"3000|3001"}'
          action: drop

  - job_name: decoy-web-http
    static_configs:
      - targets:
          - localhost
        labels:
          job: decoy-web
          service: http
          __path__: /var/log/nginx/access.log*
    pipeline_stages:
      - json:
          expressions:
            src_ip: remote_addr
            forwarded_for: x_forwarded_for
            method: method
            path: path
            status: status
            user_agent: user_agent
            post_data: post_data
      - regex:
          source: post_data
          expression: '(?:^|&)username=(?P<username>[^&]*)&password=(?P<password>[^&]*)'
      - labels:
          src_ip:
          forwarded_for:
          method:
          path:
          status:
          user_agent:
          username:
          password:
